# Generated by Django 4.0.3 on 2022-04-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='query',
            field=models.TextField(max_length=500),
        ),
    ]
